# Comprehensive Mapping for Stage Analysis Benchmarking
# Format: { "yfinance_industry_string": "Passive_ETF_Ticker" }

INDUSTRY_MAP = {
    # --- TECHNOLOGY ---
    "Communication Equipment": "IGN",
    "Computer Hardware": "XLK",
    "Consumer Electronics": "XLK",
    "Electronic Components": "XITK",
    "Electronics & Computer Distribution": "XLK",
    "Information Technology Services": "IYY",
    "Scientific & Technical Instruments": "XLK",
    "Semiconductor Equipment & Materials": "XSD",
    "Semiconductors": "SMH",
    "Software - Application": "XSW",
    "Software - Infrastructure": "IGV",

    # --- COMMUNICATION SERVICES ---
    "Advertising Agencies": "XLC",
    "Broadcasting": "XLC",
    "Communication Services": "XLC",
    "Entertainment": "XLC",
    "Internet Content & Information": "FDN",
    "Publishing": "XLC",
    "Telecom Services": "VOX",

    # --- HEALTHCARE ---
    "Biotechnology": "XBI",
    "Diagnostics & Research": "IDNA",
    "Drug Manufacturers—General": "PPH",
    "Drug Manufacturers—Specialty & Generic": "PPH",
    "Healthcare Plans": "IHF",
    "Health Information Services": "XLV",
    "Medical Care Facilities": "XHS",
    "Medical Devices": "IHI",
    "Medical Instruments & Supplies": "XHE",
    "Pharmaceutical Retailers": "XLP",

    # --- FINANCIAL SERVICES ---
    "Asset Management": "XLF",
    "Banks—Diversified": "KBE",
    "Banks—Regional": "KRE",
    "Capital Markets": "KCE",
    "Credit Services": "XLF",
    "Financial Data & Stock Exchanges": "XLF",
    "Insurance Brokers": "KIE",
    "Insurance—Diversified": "KIE",
    "Insurance—Life": "IAK",
    "Insurance—Property & Casualty": "KIE",
    "Insurance—Reinsurance": "KIE",
    "Insurance—Specialty": "KIE",
    "Mortgage Finance": "XLF",

    # --- INDUSTRIALS ---
    "Aerospace & Defense": "XAR",
    "Airlines": "JETS",
    "Air Freight & Logistics": "IYT",
    "Building Products & Equipment": "XHB",
    "Business Equipment & Supplies": "XLI",
    "Conglomerates": "XLI",
    "Consulting Services": "XLI",
    "Electrical Equipment & Parts": "XLI",
    "Engineering & Construction": "PKB",
    "Farm & Heavy Construction Machinery": "XLI",
    "Industrial Distribution": "XLI",
    "Integrated Freight & Logistics": "IYT",
    "Marine Shipping": "XLI",
    "Metal Fabrication": "XLI",
    "Pollution & Treatment Controls": "XLI",
    "Railroads": "IYT",
    "Rental & Leasing Services": "XLI",
    "Security & Protection Services": "XLI",
    "Specialty Business Services": "XLI",
    "Staffing & Employment Services": "XLI",
    "Tools & Accessories": "XLI",
    "Trucking": "XTN",
    "Waste Management": "XLI",

    # --- ENERGY ---
    "Oil & Gas Drilling": "OIH",
    "Oil & Gas E&P": "XOP",
    "Oil & Gas Equipment & Services": "OIH",
    "Oil & Gas Integrated": "XLE",
    "Oil & Gas Midstream": "AMLP",
    "Oil & Gas Refining & Marketing": "XLE",
    "Solar": "TAN",
    "Thermal Coal": "XME",
    "Uranium": "URA",

    # --- BASIC MATERIALS ---
    "Agricultural Inputs": "XLB",
    "Aluminum": "XLB",
    "Building Materials": "XHB",
    "Chemicals": "XLB",
    "Coking Coal": "XME",
    "Copper": "COPX",
    "Gold": "GDX",
    "Lumber & Wood Production": "WOOD",
    "Other Industrial Metals & Mining": "XME",
    "Other Precious Metals & Mining": "XME",
    "Paper & Paper Products": "XLB",
    "Silver": "SIL",
    "Specialty Chemicals": "XLB",
    "Steel": "SLX",

    # --- CONSUMER CYCLICAL ---
    "Apparel Manufacturing": "XLY",
    "Apparel Retail": "XRT",
    "Auto & Truck Dealerships": "XLY",
    "Auto Manufacturers": "CARZ",
    "Auto Parts": "XLY",
    "Footwear & Accessories": "XLY",
    "Gambling": "BJK",
    "Home Improvement Retail": "XRT",
    "Internet Retail": "IBUY",
    "Leisure": "XLY",
    "Lodging": "XLY",
    "Luxury Goods": "XLY",
    "Packaging & Containers": "XLB",
    "Personal Services": "XLY",
    "Residential Construction": "ITB",
    "Resorts & Casinos": "BJK",
    "Restaurants": "EATZ",
    "Specialty Retail": "XRT",
    "Textile Manufacturing": "XLY",
    "Travel Services": "JETS",

    # --- CONSUMER DEFENSIVE ---
    "Beverages—Brewers": "XLP",
    "Beverages—Non-Alcoholic": "XLP",
    "Beverages—Wine & Spirits": "XLP",
    "Confectioners": "XLP",
    "Discount Stores": "XLP",
    "Education & Training Services": "XLY",
    "Farm Products": "XLP",
    "Food Distribution": "XLP",
    "Grocery Stores": "XLP",
    "Household & Personal Products": "XLP",
    "Packaged Foods": "PBJ",
    "Tobacco": "XLP",

    # --- REAL ESTATE ---
    "Real Estate Services": "XLRE",
    "REIT—Diversified": "XLRE",
    "REIT—Healthcare Facilities": "OLD",
    "REIT—Hotel & Motel": "XLRE",
    "REIT—Industrial": "INDS",
    "REIT—Mortgage": "REM",
    "REIT—Office": "SRVR",
    "REIT—Residential": "REZ",
    "REIT—Retail": "RTL",
    "REIT—Specialty": "SRVR",

    # --- UTILITIES ---
    "Utilities—Diversified": "XLU",
    "Utilities—Independent Power Producers": "XLU",
    "Utilities—Regulated Electric": "XLU",
    "Utilities—Regulated Gas": "XLU",
    "Utilities—Regulated Water": "PHO",
    "Utilities—Renewable": "ICLN"
}

# --- Recommended Macro Fallbacks ---
SECTOR_MAP = {
    "Technology": "XLK",
    "Healthcare": "XLV",
    "Financial Services": "XLF",
    "Energy": "XLE",
    "Consumer Cyclical": "XLY",
    "Consumer Defensive": "XLP",
    "Industrials": "XLI",
    "Utilities": "XLU",
    "Basic Materials": "XLB",
    "Real Estate": "XLRE",
    "Communication Services": "XLC"
}